"""Validator for theme packages to ensure they don't contain reserved paths."""

import re
from pathlib import Path

# Paths a theme package may never ship. Folio owns and (re)generates these at
# build time; a package copy would either be clobbered by codegen or freeze a
# generated file at the bundled version. Note that theme/project-theme.ts is
# deliberately NOT reserved: packages may own the preset implementation (see
# docs/guide/theming/theme-packages.md), while theme/theme-contract.generated.ts
# is always regenerated by Folio and therefore reserved.
RESERVED_PATHS = {
    "content/",
    "lib/folio-template.ts",
    "lib/folio-mdx-contract.ts",
    "theme/theme-contract.generated.ts",
    ".next/",
    "node_modules/",
}

REQUIRED_EXPORTS_BY_FILE = {
    "theme/project-theme.ts": ["projectThemePreset", "projectThemeDefaultConfig"]
}


def _validate_theme_package(path: Path) -> list[str]:
    """
    Validate a theme package for common issues.

    Returns a list of error messages. Empty list means valid.
    """
    errors = []

    # Check if path exists and is a directory
    if not path.exists():
        errors.append(f"Theme package path '{path}' not found.")
        return errors

    if not path.is_dir():
        errors.append(f"Theme package path '{path}' is not a directory.")
        return errors

    # Check for reserved paths
    for reserved in RESERVED_PATHS:
        reserved_path = path / reserved
        if reserved_path.exists():
            if reserved.endswith("/"):
                # Directory
                errors.append(
                    f"Theme package must not contain reserved path '{reserved}'. "
                    f"Folio generates this at build time."
                )
            else:
                # File
                errors.append(
                    f"Theme package must not contain reserved file '{reserved}'. "
                    f"This is a Folio internal file."
                )

    # Check required exports in specific files
    for file_path_str, required_exports in REQUIRED_EXPORTS_BY_FILE.items():
        file_path = path / file_path_str
        if file_path.exists():
            content = file_path.read_text()
            for export_name in required_exports:
                # Match the name as a whole word following `export` (e.g.
                # `export const projectThemePreset` or `export { foo as
                # projectThemePreset }`), while ignoring the source side of an
                # alias (`export { projectThemePreset as foo }`) and unrelated
                # names such as `projectThemePresetX`.
                name_re = re.escape(export_name)
                export_pattern = rf"\bexport\b[^;]*?\b{name_re}\b(?!\s+as\b)"
                if not re.search(export_pattern, content):
                    errors.append(
                        f"{file_path_str} must export '{export_name}'. "
                        f"Expected: export const {export_name} = ..."
                    )

    return errors


def validate_and_raise(path: Path) -> None:
    """
    Validate a theme package and raise ValueError if validation fails.

    Raises:
        ValueError: If validation fails with all error messages joined.
    """
    errors = _validate_theme_package(path)
    if errors:
        error_list = "\n  - ".join([""] + errors)
        raise ValueError(f"Theme package validation failed:{error_list}")
