"""First-party kanban plugin: owns the ``kanban:`` docs.yaml key.

The board is git-persisted: the committed YAML is the source of truth.
In the browser, cards can be dragged between columns; moves are stored as a
localStorage overlay keyed to the committed board, and the exports produce
ready-to-commit move commands that close the loop. Columns are loaded from
a cardfile board directory named by ``kanban.source`` — a ``board.yaml``
schema file plus one Markdown file per card under ``cards/``, all versioned
with the project sources. The ``kanban.routes.public`` setting accepts a path
to choose where the board view is published (``"/"`` for the front page).
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import quote

from folio.generator.sidebar import _slugify
from folio.parser.markdown_parser import source_route
from folio.plugin import PluginDocument, hookimpl

FOLIO_PLUGIN_API = "1.1"

DEFAULT_ROUTES = {"docs": True, "public": False}
DEFAULT_TITLE = "Kanban"

KANBAN_TYPES = (
    "export interface KanbanArtifact {\n"
    "  kind: string\n"
    "  target: string\n"
    "  display: string\n"
    "  label: string\n"
    "  href: string\n"
    "}\n\n"
    "export interface KanbanCriterion {\n"
    "  text: string\n"
    "  done: boolean\n"
    "}\n\n"
    "export interface KanbanTrailEntry {\n"
    "  date: string\n"
    "  actor: string\n"
    "  ref: string\n"
    "  note: string\n"
    "  href: string\n"
    "}\n\n"
    "export interface KanbanComment {\n"
    "  date: string\n"
    "  actor: string\n"
    "  text: string\n"
    "}\n\n"
    "export interface KanbanCard {\n"
    "  id: string\n"
    "  title: string\n"
    "  description: string\n"
    "  tags: string[]\n"
    "  assignee: string[]\n"
    "  type: string\n"
    "  size: string\n"
    "  icon: string\n"
    "  iconTag: string\n"
    "  source: string\n"
    "  link: string\n"
    "  priority: string\n"
    "  parent: string\n"
    "  blocked_by: string[]\n"
    "  created: string\n"
    "  milestone: string\n"
    "  artifacts: KanbanArtifact[]\n"
    "  criteria: KanbanCriterion[]\n"
    "  trail: KanbanTrailEntry[]\n"
    "  comments: KanbanComment[]\n"
    "  phase: string\n"
    "  phaseTitle: string\n"
    "  file: string\n"
    "}\n\n"
    "export interface KanbanColumn {\n"
    "  id: string\n"
    "  title: string\n"
    "  limit: number | null\n"
    "  cards: KanbanCard[]\n"
    "}\n"
)

# Present in every page this plugin generates; used to tell a page the plugin
# wrote on a prior build (safe to refresh) from a page the user authored
# (never touched).
_GENERATED_PAGE_MARKER = "generated by the official `folio.plugins.kanban` plugin"
# The folder the board's docs presence lives in. The board page (or the
# forwarding page) compiles at its index; card documents compile below its
# `cards/` subtree, so pages a project authors under `kanban/` and the
# board's working papers never contend for the same slugs.
_BOARD_ROUTE_ROOT = "kanban"
_GENERATED_DOCS_ROUTE = f"{_BOARD_ROUTE_ROOT}/index"
_LEGACY_GENERATED_DOCS_ROUTE = _BOARD_ROUTE_ROOT

# ``[`` / ``]`` are escaped so a configured title cannot smuggle a markdown
# link (e.g. ``[click](javascript:...)``) into the generated heading, which
# would bypass the href scheme policy card links get via ``_theme_href``.
_MDX_TEXT_SPECIALS_RE = re.compile(r"([\\`{}<>\[\]])")

# Where a card's own files are published. Under folio's static namespace
# rather than beside the board's route, so it cannot collide with a page and
# reads as what it is: emitted output, not authored content. The template
# already links into this tree for page markdown.
_CARD_ASSET_ROOT = "_folio/kanban"

# Content route the markdown in a card's directory is built at. A card's
# prose output is a page like any other page folio makes, so it goes through
# the same content tree rather than being served as source. It sits one
# level below the board's folder so the `kanban/` slugs stay free for
# authored documentation about the board itself.
_CARD_PAGE_ROOT = f"{_BOARD_ROUTE_ROOT}/cards"


@hookimpl
def config_keys() -> list[str]:
    return ["kanban"]


# tryfirst: parse the `kanban:` key before any project plugin's configure()
# runs, so project plugins can override config.extra["kanban"] (default
# plugins register first and folio's isolated dispatch is LIFO, which would
# otherwise run this hook after — and clobber — project configure() hooks).
@hookimpl(tryfirst=True)
def configure(config: Any, raw_config: dict[str, Any]) -> None:
    # The plugin is loaded for every build as a first-party default; the
    # `kanban:` config key is what activates it. Without the key the plugin
    # stays inert (no config.extra entry, no components, no routes).
    if "kanban" not in raw_config:
        return
    project_dir = Path(getattr(config, "project_dir", "") or ".")
    kanban = normalize_kanban(
        raw_config.get("kanban", {}),
        project_dir=project_dir,
    )

    # Guard: public route cannot collide with docs route base.
    # Checked here (not in normalize_kanban) because config is needed to read
    # the docs_route_base, and normalize_kanban receives only the kanban section.
    public_route = kanban["routes"].get("public")
    if isinstance(public_route, str):
        docs_base = _docs_route_base(config)
        # Check if public route equals or sits under docs base
        if public_route == docs_base or public_route.startswith(docs_base + "/"):
            raise ValueError(
                f"kanban: routes.public path '{public_route}' collides with the docs "
                f"route base '{docs_base}' — a view there would be shadowed by the "
                "docs catch-all and fail the export far from the config error"
            )

    # Guard: public route "/" cannot coexist with a landing section.
    # Checked here (not in normalize_kanban) because raw_config is needed to see
    # the landing section, and normalize_kanban receives only the kanban section.
    if public_route == "/" and "landing" in raw_config:
        raise ValueError(
            "kanban: routes.public cannot be '/' when the config has a landing: "
            "section — the landing owns the root, and a silent clobber is forbidden"
        )

    _resolve_card_paths(kanban)
    _resolve_artifact_hrefs(
        kanban,
        docs_route_base=_docs_route_base(config),
        project_dir=project_dir,
        doc_sources=_doc_source_dirs(config, project_dir),
        # configure runs once per build, so the unreachable-doc warning
        # says its piece exactly once; the re-normalization passes stay
        # silent about it.
        warn_unreachable=True,
    )
    _resolve_roadmap_phases(kanban, raw_roadmap=raw_config.get("roadmap"))
    config.extra["kanban"] = kanban


def _resolve_roadmap_phases(kanban: dict[str, Any], *, raw_roadmap: Any) -> None:
    """Name the roadmap step each card's milestone points at.

    The roadmap already deep-links into the board with ``?milestone=<version>``.
    This is the return path, and it costs nothing to build because both halves
    are declared in the same ``docs.yaml``: a phase carries an ``id`` (its
    anchor) and a ``title``, and a card carries the ``version`` that matches.

    A card keeps its milestone whether or not a phase claims it, so a board
    with no roadmap section, or a milestone the roadmap has not reached yet,
    renders exactly as before — and an unclaimed one now says so, one grouped
    warning per milestone naming its cards and the known versions, so the
    roadmap works as the milestone registry formats.md promised.
    """
    if not isinstance(raw_roadmap, dict):
        return
    phases = raw_roadmap.get("phases")
    if not isinstance(phases, list):
        return
    by_version: dict[str, tuple[str, str]] = {}
    for phase in phases:
        if not isinstance(phase, dict):
            continue
        version = str(phase.get("version", "")).strip().lstrip("vV")
        anchor = str(phase.get("id", "")).strip()
        if version and anchor:
            by_version[version] = (anchor, str(phase.get("title", "")).strip())
    if not by_version:
        return
    unclaimed: dict[str, list[str]] = {}
    for column in kanban.get("columns", []):
        for card in column.get("cards", []):
            milestone = str(card.get("milestone", "")).strip()
            if not milestone:
                continue
            found = by_version.get(milestone)
            if found:
                card["phase"], card["phaseTitle"] = found
            else:
                unclaimed.setdefault(milestone, []).append(
                    str(card.get("id", "") or card.get("title", ""))
                )
    for milestone, cards in unclaimed.items():
        warnings.warn(
            f"kanban: milestone '{milestone}' matches no roadmap phase "
            f"(cards: {', '.join(cards)}; known: {', '.join(by_version)})",
            stacklevel=2,
        )


def _resolve_card_paths(kanban: dict[str, Any]) -> None:
    """Fill each card's ``file``: where it lives, as a project-relative path.

    A path, never a URL. This used to be two hosting-provider links —
    ``{repo}/blob/...`` for the path chip and ``{repo}/edit/...`` behind the
    dialog's pen — so "edit this card" navigated to a web editor nobody edits
    in, and to the wrong place entirely for a board that is not on that
    provider. Artifact and trail refs were resolved the same way.

    The board is operated locally, through the CLI and an editor, so the honest
    answer to "where do I change this" is the path itself. Rendering it is the
    reader's job; a static page cannot open an editor and should not pretend
    otherwise.
    """
    card_dir = kanban.get("cardDir") or ""
    if not card_dir:
        return
    for column in kanban.get("columns", []):
        for card in column.get("cards", []):
            if card.get("id"):
                card["file"] = f"{card_dir}/cards/{card['id']}.md"


def _docs_route_base(config: Any) -> str:
    """Where content pages are served from, defaulting like the builder does."""
    return str(getattr(config, "docs_route_base", "") or "/docs")


def _resolve_artifact_hrefs(
    kanban: dict[str, Any],
    *,
    docs_route_base: str,
    project_dir: Path,
    doc_sources: list[Path] | tuple[Path, ...] = (),
    warn_unreachable: bool = False,
) -> None:
    """Give an artifact that names a published page or file somewhere to open.

    A card may keep a directory of its own next to its markdown file —
    ``board/cards/<id>.md`` and ``board/cards/<id>/`` — and what is in it is
    that card's own output: the prototype a decision was made on, the document
    that compared them. ``emit_assets`` publishes that directory, so a ``doc:``
    or ``file:`` artifact pointing into it becomes a link instead of a path the
    reader has to go find. The whole directory is published, not only the
    attached files, because those files reference each other: a prototype page
    without its stylesheet opens as nothing.

    Markdown resolves to the page it was built into, not to the file. It went
    through the same parser and MDX writer as every documentation page, so
    there is a real page to send the reader to, and sending them to the source
    instead would be handing over an unstyled download of something the site
    already renders. The same reasoning covers a ``doc:`` naming a file under
    a docs source: the site publishes exactly that page, so the artifact links
    to it.

    Everywhere else, an artifact keeps the empty href it had and renders as
    the path it is. Attaching a file is not a licence to publish an arbitrary
    part of the repository — only what a card owns or the docs already
    publish opens. Under ``warn_unreachable`` (configure's one pass, so a
    build says it once) a ``doc:`` whose file exists but whose page nothing
    publishes warns, naming the card and the target as written: a ``doc:``
    promised a page, and the promise did not hold.
    """
    card_dir = kanban.get("cardDir") or ""
    if not card_dir:
        return
    route_base = docs_route_base.rstrip("/") or "/docs"
    project_root = project_dir.resolve()
    for column in kanban.get("columns", []):
        for card in column.get("cards", []):
            card_id = card.get("id")
            if not card_id:
                continue
            for artifact in card.get("artifacts", []):
                if artifact.get("kind") not in ("doc", "file"):
                    continue
                target = str(artifact.get("target", ""))
                target_path, _, raw_fragment = target.partition("#")
                fragment = f"#{raw_fragment}" if raw_fragment else ""
                relative = _owned_card_artifact(
                    project_dir,
                    card_dir=card_dir,
                    card_id=str(card_id),
                    target=target_path,
                )
                if relative is not None:
                    # Site-absolute: the same data module feeds the standalone
                    # board and any docs page that embeds it, and those sit at
                    # different depths. The template adds the base path, the
                    # way every other emitted link in it does.
                    path = relative
                    if path.suffix.lower() in {
                        ".md",
                        ".mdx",
                    } and not path.name.startswith("_"):
                        route = _card_page_route(card_id, path)
                        public_route = route.removesuffix("/index")
                        artifact["href"] = f"{route_base}/{public_route}/{fragment}"
                    else:
                        artifact["href"] = (
                            f"/{_CARD_ASSET_ROOT}/{card_id}/"
                            f"{relative.as_posix()}{fragment}"
                        )
                    continue
                if artifact.get("kind") != "doc":
                    continue
                route = _docs_source_route(project_root / target_path, doc_sources)
                if route is not None:
                    public_route = (
                        "" if route == "index" else route.removesuffix("/index")
                    )
                    artifact["href"] = (
                        f"{route_base}/{public_route}/{fragment}"
                        if public_route
                        else f"{route_base}/{fragment}"
                    )
                elif warn_unreachable and (project_root / target_path).is_file():
                    warnings.warn(
                        f"kanban: card '{card_id}': doc artifact "
                        f"'{artifact.get('display') or target}' has no "
                        "published page — neither the card's directory nor a "
                        "docs source publishes it",
                        stacklevel=2,
                    )


def _docs_source_route(target: Path, doc_sources) -> str | None:
    """The content route a docs source builds for ``target``, or ``None``.

    The route rule is ``source_route``, the one ``parse_markdown_directory``
    applies to every docs source — one rule, imported, so the two can never
    drift. ``.md`` only: that is all a docs source reads.
    """
    if target.suffix != ".md":
        return None
    resolved = target.resolve()
    if not resolved.is_file():
        return None
    for source in doc_sources:
        try:
            relative = resolved.relative_to(source)
        except ValueError:
            continue
        return source_route(relative)
    return None


def _doc_source_dirs(config: Any, project_dir: Path) -> list[Path]:
    """Docs source directories as resolved absolute paths.

    ``config.doc_sources`` is relative before ``resolve_paths`` runs and
    absolute after; resolving against the project directory accepts both.
    """
    dirs: list[Path] = []
    for source in getattr(config, "doc_sources", None) or []:
        path = Path(str(source))
        if not path.is_absolute():
            path = project_dir / path
        dirs.append(path.resolve())
    return dirs


def _owned_card_artifact(
    project_dir: Path,
    *,
    card_dir: str,
    card_id: str,
    target: str,
) -> Path | None:
    """Return a safe card-relative target, or ``None`` when it is not owned."""
    if not target or Path(target).is_absolute():
        return None
    project_root = project_dir.resolve()
    cards_root = project_root / card_dir / "cards"
    source_dir = cards_root / card_id
    if source_dir.is_symlink() or not source_dir.is_dir():
        return None
    resolved_cards = cards_root.resolve()
    resolved_source = source_dir.resolve()
    if not resolved_cards.is_relative_to(
        project_root
    ) or not resolved_source.is_relative_to(resolved_cards):
        return None
    lexical_target = project_root / target
    if _path_has_symlink(project_root, lexical_target):
        return None
    resolved_target = lexical_target.resolve()
    try:
        relative = resolved_target.relative_to(resolved_source)
    except ValueError:
        return None
    if not relative.parts or any(part.startswith(".") for part in relative.parts):
        return None
    if not resolved_target.is_file():
        return None
    return relative


@hookimpl
def register_extensions(registry: Any, config: Any) -> None:
    kanban = active_kanban(config)
    if kanban is None:
        return

    # Re-guard because project plugins may override config.extra["kanban"] after
    # configure(), reaching this hook with a route that bypassed configure's guards.
    # active_kanban re-normalizes the routes, but does not validate them.
    public_route = kanban["routes"].get("public")
    if isinstance(public_route, str):
        docs_base = _docs_route_base(config)
        if public_route == docs_base or public_route.startswith(docs_base + "/"):
            raise ValueError(
                f"kanban: routes.public path '{public_route}' collides with the docs "
                f"route base '{docs_base}' — a view there would be shadowed by the "
                "docs catch-all and fail the export far from the config error"
            )
    # config.landing_enabled is set by the landing plugin's configure() hook and
    # survives resolve_paths (config.py:185), so it's the reliable source of truth.
    if public_route == "/" and getattr(config, "landing_enabled", False):
        raise ValueError(
            "kanban: routes.public cannot be '/' when landing is enabled — "
            "the landing owns the root, and a silent clobber is forbidden"
        )

    registry.register_component(
        "KanbanBoard",
        import_path="@/components/kanban-board",
        expose_mdx=True,
        props={
            "columns": "KanbanColumn[] | undefined",
            "compact": "boolean | undefined",
            "maxCardsPerColumn": "number | undefined",
            "title": "string | undefined",
            "description": "string | undefined",
            "roadmapHref": "string | undefined",
            "workspace": "boolean | undefined",
        },
    )
    registry.register_component(
        "RedirectPage",
        import_path="@/components/redirect-page",
        expose_mdx=False,
        props={
            "to": "string",
        },
    )
    registry.write_data_module(
        "kanban",
        export_name="kanbanColumns",
        data=kanban["columns"],
        type_source=KANBAN_TYPES,
        type_annotation="KanbanColumn[]",
        module_path="kanban-data",
    )

    public_route = kanban["routes"].get("public")
    if public_route:
        # The board is a working surface, not a reading one: `dense` drops
        # the layout band entirely and the board carries its own masthead,
        # so the page opens on the work.
        props: dict[str, Any] = {"dense": True}
        title = (
            kanban["title"]
            if kanban["title"] != "Kanban"
            else f"{config.project_name} Kanban"
        )
        board_props: dict[str, Any] = {"title": title}
        raw = getattr(config, "extra", {}).get("kanban")
        description = raw.get("description") if isinstance(raw, dict) else None
        if isinstance(description, str) and description.strip():
            props["description"] = description.strip()
            board_props["description"] = description.strip()
        # A card's milestone links to the roadmap step it names, which is the
        # return path for the roadmap's own ?milestone= link into the board.
        # The href is a prop rather than baked into the card data because the
        # data module is shared by every view and each sits at its own depth.
        # Depth: count non-empty segments; roadmapHref: "../" per depth, then "roadmap/".
        view_path = public_route if isinstance(public_route, str) else "/kanban"
        depth = len([s for s in view_path.split("/") if s])
        roadmap_cfg = getattr(config, "extra", {}).get("roadmap")
        roadmap_public = isinstance(roadmap_cfg, dict) and bool(
            (roadmap_cfg.get("routes") or {}).get("public")
        )
        if roadmap_public:
            board_props["roadmapHref"] = "../" * depth + "roadmap/"
        # The standalone page is the one context where the board is an app:
        # a viewport-height workspace under the navbar, the composer rail as
        # a full-height panel, the columns scrolling inside a canvas. The
        # same component embedded in docs prose (or as a miniature) keeps
        # the in-flow layout, so the mode is a prop only this emitted page
        # sets — and the layout gets the same flag, because its vertical
        # frame padding would otherwise scroll the page by exactly that
        # padding under a viewport-height section.
        board_props["workspace"] = True
        props["workspace"] = True
        registry.add_view(
            path=view_path,
            layout="folio.public",
            title=title,
            props=props,
            slots={"main": [{"component": "KanbanBoard", "props": board_props}]},
        )

        # When the board is not at /kanban, register a redirect view at /kanban
        # that forwards to the configured path, preserving query and hash. This
        # keeps published /kanban/?q= links (agents.md, board/SKILL.md) working.
        if view_path != "/kanban":
            # Compute relative path from /kanban/ to view_path
            # Root "/" -> "../", "/board" -> "../board/", etc.
            # Strip leading/trailing slashes and collapse empty segments
            segments = [s for s in view_path.strip("/").split("/") if s]
            if segments:
                redirect_to = "../" + "/".join(segments) + "/"
            else:
                # Root case: "/" -> "../"
                redirect_to = "../"

            registry.add_view(
                path="/kanban",
                layout="folio.public",
                title=title,
                props={"dense": True},
                slots={
                    "main": [
                        {"component": "RedirectPage", "props": {"to": redirect_to}}
                    ]
                },
            )


@hookimpl
def collect_docs(config: Any) -> list[PluginDocument]:
    """Contribute card-owned Markdown to Folio's core document pipeline."""
    kanban = active_kanban(config)
    if kanban is None:
        return []
    project_dir = Path(getattr(config, "project_dir", "") or ".")
    # Unlisted: a card's output answers to its URL and stays findable — in
    # search, the sitemap, llms.txt, and the Markdown mirrors — but board
    # working papers have no place in the docs sidebar's teaching order.
    return [
        PluginDocument(source=source, route=route, unlisted=True)
        for _card, source, route in _iter_card_docs(kanban, project_dir=project_dir)
    ]


def _iter_card_docs(kanban: dict[str, Any], *, project_dir: Path):
    """Yield ``(card, source, route)`` for every markdown file a card owns.

    One iteration feeds both ``collect_docs`` and the generated card index,
    so the pages a card contributes and the pages its index lists cannot
    drift apart.
    """
    for card, source, relative in _iter_card_files(kanban, project_dir=project_dir):
        if source.suffix.lower() not in {".md", ".mdx"}:
            continue
        # `_TEMPLATE.md` means "not a card"; the same mark on any path part —
        # file or directory — means "not a page". The raw bundle still
        # carries these files; only compilation is declined.
        if any(part.startswith("_") for part in relative.parts):
            continue
        yield (
            card,
            source,
            _card_page_route(relative=relative, card_id=str(card.get("id", ""))),
        )


@hookimpl
def watch_paths(config: Any) -> list[str]:
    """The serve watcher asks what to watch beyond code and docs: a cardfile
    board answers with its directory, so a card edited mid-serve reaches the
    served board without a restart."""
    kanban = active_kanban(config)
    if not kanban or not kanban.get("cardDir"):
        return []
    project_dir = Path(getattr(config, "project_dir", "") or ".")
    return [str(project_dir / kanban["cardDir"])]


@hookimpl
def on_watched_change(builder: Any, config: Any, path: str, change: str) -> bool:
    """Reload the board from disk when anything under it changes.

    The whole board reloads rather than one card: membership, ordering, and
    the column set all live across files, and a full load is the same work
    the build does. A half-saved card raises out of ``normalize_kanban``;
    the watcher's isolation degrades that to a warning and the next save
    lands cleanly. Card-directory documents republish as raw assets here;
    their compiled pages still come from a full build. The section is
    reconstructed from ``config.extra``, not re-read from ``docs.yaml`` —
    the config file is not watched, so config edits mid-serve still take a
    restart."""
    kanban = active_kanban(config)
    if not kanban or not kanban.get("cardDir"):
        return False
    project_dir = Path(getattr(config, "project_dir", "") or ".")
    board_dir = (project_dir / kanban["cardDir"]).resolve()
    try:
        Path(path).resolve().relative_to(board_dir)
    except ValueError:
        return False

    raw: dict[str, Any] = {
        "source": kanban["cardDir"],
        "routes": dict(kanban["routes"]),
    }
    if kanban.get("title"):
        raw["title"] = kanban["title"]
    if kanban.get("description"):
        raw["description"] = kanban["description"]
    config.extra["kanban"] = normalize_kanban(raw, project_dir=project_dir)
    emit_assets(builder, config)
    # The served board reads lib/kanban-data.ts, which the extension
    # emitter writes from the registry — emit_assets alone refreshes the
    # pages but not the data module the component imports. Re-registering
    # this plugin's own extensions and re-applying them rewrites it (and
    # the plugin's view pages, idempotently). The builder's view-route set
    # narrows to this plugin's views until the next full build; only the
    # build-time link checker reads it, so a serve session never notices.
    apply_extensions = getattr(builder, "apply_extensions", None)
    if callable(apply_extensions):
        from folio.extensions import ExtensionRegistry, register_builtin_extensions

        registry = ExtensionRegistry()
        register_builtin_extensions(registry)
        register_extensions(registry, config)
        apply_extensions(registry)
    write_search_index = getattr(builder, "write_search_index", None)
    if callable(write_search_index):
        write_search_index()
    return True


@hookimpl
def emit_assets(builder: Any, config: Any) -> None:
    # This namespace is owned by the kanban plugin even when the feature is
    # disabled on a warm build. Clearing first prevents a removed `kanban:`
    # section from leaving its old artifact bundle online.
    remove_static_tree = getattr(builder, "remove_static_tree", None)
    if callable(remove_static_tree):
        remove_static_tree(_CARD_ASSET_ROOT)

    kanban = active_kanban(config)
    if kanban is None:
        # The generated pages are as owned as the static namespace above: a
        # removed `kanban:` section must not leave last build's board page or
        # card indexes published.
        _remove_generated_page(builder)
        _remove_stale_card_indexes(builder, keep={})
        return

    # Before the docs-route branch: a board with `routes.docs: false` still
    # has a standalone page, and its cards still have artifacts to open.
    _publish_card_assets(
        builder, kanban, project_dir=Path(getattr(config, "project_dir", "") or ".")
    )

    docs_route_on = bool(kanban["routes"].get("docs"))
    if docs_route_on:
        _sync_board_page(builder, kanban)
    # Card documents publish under the docs route regardless of the board's
    # own docs page (`collect_docs` contributes them either way), so the
    # folder indexes above them are synced either way too.
    _sync_card_index_pages(
        builder,
        kanban,
        project_dir=Path(getattr(config, "project_dir", "") or "."),
        route_base=_docs_route_base(config),
        docs_route_on=docs_route_on,
    )


def _sync_board_page(builder: Any, kanban: dict[str, Any]) -> None:
    """Write or refresh the generated board page at ``kanban/index``."""
    # Artifact documents live below `kanban/cards/<card>/...`, so the board
    # page is the folder index. Migrate the old sibling `kanban.mdx` on a warm build;
    # a user-authored page at that route still wins and is never touched.
    if builder.page_exists(_LEGACY_GENERATED_DOCS_ROUTE):
        legacy = _read_page(builder, _LEGACY_GENERATED_DOCS_ROUTE)
        if legacy is None or _GENERATED_PAGE_MARKER not in legacy:
            builder.register_route(_LEGACY_GENERATED_DOCS_ROUTE)
            return
        remove_page = getattr(builder, "remove_page", None)
        if not callable(remove_page):
            builder.register_route(_LEGACY_GENERATED_DOCS_ROUTE)
            return
        remove_page(_LEGACY_GENERATED_DOCS_ROUTE)

    # Declare the route as live even when the page persists from a prior
    # build, so internal links to it are not flagged broken.
    builder.register_route(_GENERATED_DOCS_ROUTE)
    content = docs_page_mdx(kanban)
    if not builder.page_exists(_GENERATED_DOCS_ROUTE):
        builder.write_page(_GENERATED_DOCS_ROUTE, content)
        return
    # Write-if-changed: refresh a page this plugin generated on a prior
    # build (e.g. the configured title changed), but never overwrite a
    # user-authored page at the same route. When the builder cannot read
    # pages the content is unknown, so the page is conservatively left
    # alone (folio's SiteBuilder always exposes read_page).
    existing = _read_page(builder, _GENERATED_DOCS_ROUTE)
    if existing is None:
        return
    if _GENERATED_PAGE_MARKER in existing and existing != content:
        builder.write_page(_GENERATED_DOCS_ROUTE, content)


# A generated folder index lives at `kanban/cards/index` or deeper, one per
# folder a card's documents sit under. The same pattern still matches the
# pre-`cards/` shape (`kanban/<id>/index`), so a warm workspace sheds the old
# generation's marker pages instead of serving both. The board page
# (`kanban/index`, a single segment below the root) never matches, so the
# sweep cannot take it — and it only ever removes marker-tagged pages.
_CARD_INDEX_ROUTE_RE = re.compile(
    rf"^{re.escape(_BOARD_ROUTE_ROOT)}/[^/]+(?:/[^/]+)*/index$"
)


def _sync_card_index_pages(
    builder: Any,
    kanban: dict[str, Any],
    *,
    project_dir: Path,
    route_base: str,
    docs_route_on: bool,
) -> None:
    """Keep every folder route above a card's documents resolvable.

    A card's documents compile below its own folder route, and a folder whose
    children exist is a URL readers will try — trimmed by hand or reached from
    a breadcrumb. When the card ships no ``index.md``/``README.md`` of its
    own, a marker-tagged index listing the card's documents fills the hole;
    when it does, or when the documents are gone on a warm build, the
    generated page steps aside. User-authored pages (no marker) are never
    touched, matching the board page's contract one level down.

    The ``kanban/cards/`` folder itself resolves to a directory of the
    publishing cards. With the board's own docs page turned off the
    ``kanban/`` folder is a hole of the same kind, so ``kanban/index``
    forwards to the public board when one exists and repeats the directory
    when none does — a listing, not the board the configuration said no to.
    With no documents at all the plugin's generated pages come down and the
    namespace is silent, exactly as before.
    """
    docs_by_card: dict[str, dict[str, Any]] = {}
    for card, source, route in _iter_card_docs(kanban, project_dir=project_dir):
        entry = docs_by_card.setdefault(
            str(card.get("id", "")), {"card": card, "docs": []}
        )
        entry["docs"].append((source, route))

    status_titles = {
        str(card.get("id", "")): str(column.get("title") or "")
        for column in kanban.get("columns", [])
        for card in column.get("cards", [])
    }
    project_root = project_dir.resolve()

    wanted: dict[str, str] = {}
    for card_id, entry in docs_by_card.items():
        routes = {route for _source, route in entry["docs"]}
        card_root = f"{_CARD_PAGE_ROOT}/{card_id}"
        for folder in _folders_above(routes, root=_CARD_PAGE_ROOT):
            index_route = f"{folder}/index"
            if index_route in routes:
                # The card wrote this folder's page itself (index.md or
                # README.md); the compiled document owns the route.
                continue
            # The folder's public route may be a user-authored page — a
            # `kanban/<id>.mdx` in the project's own docs claims the same
            # URL `_canonical_doc_route` gives the index. The user wins,
            # exactly as at the board route.
            if _user_owns_route(builder, folder):
                continue
            scoped = [
                (source, route)
                for source, route in entry["docs"]
                if route.startswith(f"{folder}/")
            ]
            wanted[index_route] = card_index_mdx(
                entry["card"],
                scoped,
                route_base=route_base,
                status_title=status_titles.get(card_id, ""),
                project_root=project_root,
                subtree=None if folder == card_root else folder,
            )

    # `kanban/cards/` sits between every document and the board's folder —
    # a URL readers reach by trimming — so while anything publishes it
    # resolves to a directory of the publishing cards. A user page at the
    # route wins, exactly as at every other folder.
    if docs_by_card and not _user_owns_route(builder, _CARD_PAGE_ROOT):
        wanted[f"{_CARD_PAGE_ROOT}/index"] = kanban_directory_mdx(
            kanban, docs_by_card, route_base=route_base
        )

    if not docs_route_on:
        if docs_by_card and _user_owns_route(builder, _LEGACY_GENERATED_DOCS_ROUTE):
            # The public route of `kanban/index` is `kanban`, and a
            # user-authored legacy `kanban.mdx` holds it. Register it so
            # links to it stay valid, and take down any directory page a
            # prior build generated — the stale sweep below never matches
            # the board route.
            builder.register_route(_LEGACY_GENERATED_DOCS_ROUTE)
            _remove_marker_page(builder, _GENERATED_DOCS_ROUTE)
        elif docs_by_card:
            # Card pages are read from the board, so the folder above them
            # does not index them: it forwards to the board's public route.
            # Without one there is no board page to land on, and the folder
            # must still resolve, so the directory of publishing cards stays.
            if kanban["routes"].get("public"):
                wanted[_GENERATED_DOCS_ROUTE] = kanban_redirect_mdx(
                    kanban, route_base=route_base
                )
            else:
                wanted[_GENERATED_DOCS_ROUTE] = kanban_directory_mdx(
                    kanban, docs_by_card, route_base=route_base
                )
            _remove_marker_page(builder, _LEGACY_GENERATED_DOCS_ROUTE)
        else:
            _remove_generated_page(builder)

    _remove_stale_card_indexes(builder, keep=wanted)

    for route, content in wanted.items():
        builder.register_route(route)
        if not builder.page_exists(route):
            builder.write_page(route, content)
            continue
        existing = _read_page(builder, route)
        if (
            existing is not None
            and _GENERATED_PAGE_MARKER in existing
            and existing != content
        ):
            builder.write_page(route, content)


def _folders_above(routes: set[str], *, root: str) -> list[str]:
    """Every folder route between a document and ``root``, nearest last.

    ``kanban/cards/one-card/sub/report`` contributes
    ``kanban/cards/one-card/sub`` and ``kanban/cards/one-card``; ``root``
    itself is the caller's business and is never yielded.
    """
    folders: set[str] = set()
    for route in routes:
        parent = PurePosixPath(route).parent
        while str(parent) not in (root, "."):
            folders.add(str(parent))
            parent = parent.parent
    return sorted(folders)


def _user_owns_route(builder: Any, route: str) -> bool:
    """Whether a page the plugin did not generate sits at ``route``.

    An unreadable page counts as user-authored: when its content is unknown
    the only safe reading is that it is not ours to shadow.
    """
    if not builder.page_exists(route):
        return False
    existing = _read_page(builder, route)
    return existing is None or _GENERATED_PAGE_MARKER not in existing


def _remove_stale_card_indexes(builder: Any, *, keep: dict[str, str]) -> None:
    """Drop generated card indexes whose card stopped publishing documents."""
    list_pages = getattr(builder, "list_pages", None)
    remove_page = getattr(builder, "remove_page", None)
    if not callable(list_pages) or not callable(remove_page):
        return
    for route in list_pages(_BOARD_ROUTE_ROOT):
        if route in keep or not _CARD_INDEX_ROUTE_RE.match(route):
            continue
        existing = _read_page(builder, route)
        if existing is not None and _GENERATED_PAGE_MARKER in existing:
            remove_page(route)


# One icon per artifact kind, from the FeatureCard token set the docs
# already use. Unknown kinds read as plain files.
_ARTIFACT_TILE_ICON = {
    "doc": "book",
    "file": "code",
    "api": "api",
    "pr": "git",
    "url": "network",
}


def card_index_mdx(
    card: dict[str, Any],
    docs: list[tuple[Path, str]],
    *,
    route_base: str,
    status_title: str = "",
    project_root: Path | None = None,
    subtree: str | None = None,
) -> str:
    """The folder page for a card's published output: tiles, not a list.

    The card root gets the card's own voice — its status line, the first
    paragraph of its description, and one tile per document and artifact. A
    subtree folder stays lean: the documents below it, nothing else.
    """
    title = str(card.get("title") or card.get("id") or "Card")
    base = route_base.rstrip("/") or "/docs"
    lines = [
        f"{{/* This page is {_GENERATED_PAGE_MARKER} "
        "when a card's directory publishes documents but no index of its own. */}",
        "",
        f"# {_escape_mdx_text(title)}",
        "",
    ]

    # Curated artifact labels beat a document's own heading when both name
    # the same file, and an artifact band ships things a document list never
    # sees: the prototypes, the pull requests, the closed doors.
    by_target: dict[str, dict[str, Any]] = {}
    if subtree is None:
        for artifact in card.get("artifacts", []):
            target = str(artifact.get("target", "")).partition("#")[0]
            by_target[target] = artifact

        meta = " · ".join(
            part
            for part in (
                status_title,
                str(card.get("milestone", "")),
                str(card.get("type", "")),
                str(card.get("size", "")).upper(),
            )
            if part
        )
        if meta:
            lines.extend([f"*{_escape_mdx_text(meta)}*", ""])
        excerpt = _plain_excerpt(str(card.get("description", "")), limit=300)
        if excerpt:
            lines.extend([_escape_mdx_text(excerpt), ""])

    lines.append("<CardGrid>")
    covered: set[str] = set()
    for source, route in sorted(docs, key=lambda item: item[1]):
        relative = ""
        if project_root is not None:
            try:
                relative = source.resolve().relative_to(project_root).as_posix()
            except ValueError:
                relative = ""
        artifact = by_target.get(relative)
        if artifact is not None:
            covered.add(relative)
        label = (artifact or {}).get("label") or _doc_title(source) or source.stem
        # The public URL, not the content route: a README compiles at
        # `.../index`, which the router serves at the folder. Quoted, because
        # a route is made of file names and a `)` or a space in one would
        # otherwise cut a destination short.
        public_route = quote(route.removesuffix("/index"))
        lines.append(
            "  <FeatureCard"
            f' title="{_jsx_attr(label)}"'
            f' description="{_jsx_attr(_doc_excerpt(source) or relative or route)}"'
            f' href="{base}/{public_route}/"'
            ' icon="book" />'
        )
    if subtree is None:
        for artifact in card.get("artifacts", []):
            target = str(artifact.get("target", "")).partition("#")[0]
            if target in covered:
                continue
            kind = str(artifact.get("kind", "file"))
            # What the author wrote, not where it resolved to: a sibling's
            # display is its bare name, and the tile stops repeating the
            # directory the card index already stands in.
            display = str(artifact.get("display", "") or "") or target
            label = artifact.get("label") or (
                f"#{target}" if kind == "pr" else display.rsplit("/", 1)[-1]
            )
            href = str(artifact.get("href", ""))
            tile = (
                "  <FeatureCard"
                f' title="{_jsx_attr(label)}"'
                f' description="{_jsx_attr("#" + target if kind == "pr" else display)}"'
            )
            if href:
                tile += f' href="{_jsx_attr(href)}"'
            tile += f' icon="{_ARTIFACT_TILE_ICON.get(kind, "code")}" />'
            lines.append(tile)
    lines.extend(
        [
            "</CardGrid>",
            "",
            f"The card belongs to [the board]({base}/{_BOARD_ROUTE_ROOT}/).",
            "",
        ]
    )
    return "\n".join(lines)


def kanban_redirect_mdx(kanban: dict[str, Any], *, route_base: str) -> str:
    """The parent folder page when the board lives at a public route.

    Card documents compile below ``kanban/`` but are read from the board, so
    the folder forwards there instead of indexing them. The target is written
    relative to the folder's own depth — the page is served under the docs
    route base, and a site base path must survive — and RedirectPage carries
    query and hash across, the same contract the ``/kanban`` forwarder keeps.
    """
    depth = len([part for part in route_base.split("/") if part]) + 1
    public_route = kanban.get("routes", {}).get("public")
    view_path = public_route if isinstance(public_route, str) else "/kanban"
    segments = [part for part in view_path.strip("/").split("/") if part]
    to = "../" * depth + ("/".join(segments) + "/" if segments else "")
    return (
        'import { RedirectPage } from "@/components/redirect-page"\n\n'
        f"{{/* This page is {_GENERATED_PAGE_MARKER} "
        "when the board's docs page is off and the board lives at its public route. */}\n\n"
        f'<RedirectPage to="{_jsx_attr(to)}" />\n'
    )


def kanban_directory_mdx(
    kanban: dict[str, Any],
    docs_by_card: dict[str, dict[str, Any]],
    *,
    route_base: str,
) -> str:
    """A folder page of one tile per publishing card.

    Two routes use it. ``kanban/cards/index`` whenever anything publishes:
    the documents compile below ``cards/``, so the folder resolves to what
    it holds — what each card is about, straight from the card's own
    description. And ``kanban/index`` when the board is published nowhere at
    all, rather than the board component the configuration declined; with a
    public route that folder forwards to the board instead
    (:func:`kanban_redirect_mdx`).
    """
    title = str(kanban.get("title") or DEFAULT_TITLE)
    base = route_base.rstrip("/") or "/docs"
    lines = [
        f"{{/* This page is {_GENERATED_PAGE_MARKER} "
        "when the board's docs page is off but cards below it publish documents. */}",
        "",
        f"# {_escape_mdx_text(title)}",
        "",
    ]
    description = str(kanban.get("description") or "")
    if description:
        lines.extend([_escape_mdx_text(description), ""])
    lines.append("<CardGrid>")
    for card_id, entry in docs_by_card.items():
        card = entry["card"]
        label = str(card.get("title") or card_id)
        n_docs = len(entry.get("docs") or [])
        excerpt = _plain_excerpt(str(card.get("description", "")), limit=160)
        pages = f"{n_docs} page" + ("" if n_docs == 1 else "s")
        lines.append(
            "  <FeatureCard"
            f' title="{_jsx_attr(label)}"'
            f' description="{_jsx_attr(excerpt or pages)}"'
            f' href="{base}/{_CARD_PAGE_ROOT}/{quote(card_id)}/"'
            ' icon="dashboard" />'
        )
    lines.extend(["</CardGrid>", ""])
    return "\n".join(lines)


def _jsx_attr(value: str) -> str:
    """Make a string safe inside a double-quoted MDX component attribute."""
    flat = re.sub(r"\s+", " ", str(value)).strip()
    return flat.replace('"', "&quot;")


def _plain_excerpt(markdown_text: str, *, limit: int) -> str:
    """The first paragraph as plain prose: markup off, one line, capped."""
    body = markdown_text.strip()
    if not body:
        return ""
    paragraph = re.split(r"\n\s*\n", body, 1)[0]
    flat = re.sub(r"\s+", " ", paragraph).strip()
    flat = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", flat)
    flat = flat.replace("**", "").replace("`", "")
    if len(flat) > limit:
        cut = flat[:limit].rsplit(" ", 1)[0].rstrip(",;:")
        flat = f"{cut}…"
    return flat


def _doc_title(source: Path) -> str:
    """The document's first heading, for a link that says what it opens."""
    try:
        text = source.read_text(encoding="utf-8")
    except OSError:
        return ""
    body = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
        if line.strip() and not line.startswith("#"):
            break
    return ""


def _doc_excerpt(source: Path) -> str:
    """The document's first prose paragraph, flattened for a tile."""
    try:
        text = source.read_text(encoding="utf-8")
    except OSError:
        return ""
    body = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)
    prose: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            if prose:
                break
            continue
        if stripped.startswith("#") or stripped.startswith("```"):
            if prose:
                break
            continue
        prose.append(stripped)
    return _plain_excerpt(" ".join(prose), limit=150)


def _publish_card_assets(
    builder: Any, kanban: dict[str, Any], *, project_dir: Path
) -> None:
    """Publish each card's own directory under ``/_folio/kanban/``.

    Everything in ``board/cards/<id>/`` goes up as it is on disk: the whole
    directory, because the files in it reference each other and an attached
    page without its stylesheet is not the page.

    Markdown is the exception, and it is the point. A ``.md`` sibling is not a
    file to download, it is a page the project wrote, so it goes through the
    same pipeline every documentation page goes through — parsed, compiled to
    MDX, themed, in the search index and in ``llms.txt``. It is still copied
    here as source too, because a relative link from a prototype to it has to
    resolve, and because the raw file is what an agent reads.

    Two things never travel. A dotfile or dot-directory is session scratch by
    convention (``.verify/`` full of screenshots is what prompted the rule),
    and a symlink is refused rather than followed, so a link out of the
    project cannot publish a file the project does not contain.
    """
    copy_static_asset = getattr(builder, "copy_static_asset", None)
    if not callable(copy_static_asset):
        return
    for card, source, relative in _iter_card_files(kanban, project_dir=project_dir):
        copy_static_asset(
            f"{_CARD_ASSET_ROOT}/{card['id']}/{relative.as_posix()}", source
        )


def _iter_card_files(kanban: dict[str, Any], *, project_dir: Path):
    """Yield safe, visible files from directories owned by known cards."""
    card_dir = str(kanban.get("cardDir") or "")
    if not card_dir:
        return
    project_root = project_dir.resolve()
    cards_root = project_root / card_dir / "cards"
    resolved_cards = cards_root.resolve()
    if not resolved_cards.is_relative_to(project_root):
        return
    for column in kanban.get("columns", []):
        for card in column.get("cards", []):
            card_id = str(card.get("id") or "")
            if not card_id:
                continue
            source_dir = cards_root / card_id
            if source_dir.is_symlink() or not source_dir.is_dir():
                continue
            resolved_source = source_dir.resolve()
            if not resolved_source.is_relative_to(resolved_cards):
                continue
            for source in sorted(source_dir.rglob("*")):
                relative = source.relative_to(source_dir)
                if any(part.startswith(".") for part in relative.parts):
                    continue
                if _path_has_symlink(source_dir, source) or not source.is_file():
                    continue
                yield card, source, relative


def _path_has_symlink(root: Path, target: Path) -> bool:
    """Whether a target path traverses any symlink below ``root``."""
    try:
        relative = target.relative_to(root)
    except ValueError:
        return True
    current = root
    if current.is_symlink():
        return True
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            return True
    return False


def _card_page_route(card_id: str, relative: Path) -> str:
    """Content route for one markdown file in a card's directory."""
    without_suffix = relative.with_suffix("")
    if without_suffix.name.lower() == "readme":
        without_suffix = without_suffix.with_name("index")
    stem = without_suffix.as_posix()
    return f"{_CARD_PAGE_ROOT}/{card_id}/{stem}"


def _read_page(builder: Any, route: str) -> str | None:
    """The page content on disk, or None when the builder cannot read pages."""
    read_page = getattr(builder, "read_page", None)
    if not callable(read_page):
        return None
    return read_page(route)


def _remove_generated_page(builder: Any) -> None:
    """Remove the plugin's own marker-tagged docs page, if one persists.

    Only a page carrying the generated-page marker is removed; when the
    builder cannot read or remove pages nothing happens (better a stale
    plugin page than a deleted user page).
    """
    for route in (_GENERATED_DOCS_ROUTE, _LEGACY_GENERATED_DOCS_ROUTE):
        _remove_marker_page(builder, route)


def _remove_marker_page(builder: Any, route: str) -> None:
    """Remove one page, and only when it carries the generated-page marker."""
    remove_page = getattr(builder, "remove_page", None)
    if not callable(remove_page):
        return
    if not builder.page_exists(route):
        return
    existing = _read_page(builder, route)
    if existing is not None and _GENERATED_PAGE_MARKER in existing:
        remove_page(route)


def _normalize_route_value(value: Any) -> bool | str:
    """Normalize a route value: bool stays bool, string becomes "/"-prefixed path, else bool()."""
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            return False
        return "/" + stripped.strip("/")
    return bool(value)


def normalize_kanban(raw_kanban: Any, *, project_dir: Path) -> dict[str, Any]:
    if not isinstance(raw_kanban, dict):
        raise ValueError(
            "kanban: the section needs `source:` pointing at a board "
            "directory (board.yaml + cards/) — run `folio kanban init`"
        )
    if "columns" in raw_kanban:
        raise ValueError(
            "kanban: inline `columns:` boards were removed; a board is a "
            "directory of card files — run `folio kanban init`, or see the "
            "kanban formats page for moving a hand-written YAML board to cards"
        )
    if "source" not in raw_kanban:
        raise ValueError(
            "kanban: the section needs `source:` pointing at a board "
            "directory (board.yaml + cards/) — run `folio kanban init`"
        )

    routes = dict(DEFAULT_ROUTES)
    raw_routes = raw_kanban.get("routes", {})
    if isinstance(raw_routes, dict):
        for key in routes:
            if key in raw_routes:
                routes[key] = _normalize_route_value(raw_routes[key])

    title = raw_kanban.get("title")
    if not isinstance(title, str) or not title.strip():
        title = ""
    else:
        title = title.strip()

    description = raw_kanban.get("description")
    description = description.strip() if isinstance(description, str) else ""

    raw_columns, board_title, icons = _load_source_columns(
        raw_kanban.get("source"), project_dir=project_dir
    )
    # docs.yaml wins when both name the board; board.yaml names it otherwise.
    title = title or board_title or DEFAULT_TITLE
    columns = _normalize_columns(raw_columns)
    _resolve_card_icons(columns, icons)
    # The board directory is kept so a card can link to its own file: it is
    # the only place that knows where `cards/<id>.md` actually lives.
    raw_source = raw_kanban.get("source")
    card_dir = ""
    if isinstance(raw_source, str) and raw_source.strip():
        candidate = Path(raw_source.strip())
        if not candidate.is_absolute():
            candidate = project_dir / candidate
        card_dir = _canonical_card_dir(candidate, project_dir=project_dir)

    return {
        "routes": routes,
        "title": title,
        "columns": columns,
        "description": description,
        "cardDir": card_dir,
        "icons": icons,
    }


def _resolve_card_icons(columns: list[dict[str, Any]], icons: dict[str, str]) -> None:
    """Stamp each card with the icon of its first mapped tag.

    Resolution happens after every normalization pass because
    ``_normalize_card`` rebuilds card dicts from scratch: the icon is
    derived data, like paths and artifact hrefs, never trusted from input."""
    for column in columns:
        for card in column["cards"]:
            tag = next((tag for tag in card["tags"] if tag in icons), "")
            card["icon"] = icons[tag] if tag else ""
            card["iconTag"] = tag


def _normalize_columns(raw_columns: list[Any]) -> list[dict[str, Any]]:
    """Normalize columns and enforce board-wide unique card ids.

    Cardfile boards get uniqueness for free (one file per id); duplicates
    appearing elsewhere (synthesized ids, manual conflicts) are suffixed and
    warned about rather than dropped.
    """
    columns = [
        column
        for index, raw_column in enumerate(raw_columns)
        if (column := _normalize_column(raw_column, index)) is not None
    ]
    seen: set[str] = set()
    for column in columns:
        for card in column["cards"]:
            card_id = card["id"]
            if card_id in seen:
                suffix = 2
                while f"{card_id}-{suffix}" in seen:
                    suffix += 1
                warnings.warn(
                    f"kanban: duplicate card id '{card_id}' "
                    f"(column '{column['title']}'); renaming to "
                    f"'{card_id}-{suffix}' — give the card an explicit id",
                    stacklevel=2,
                )
                card_id = f"{card_id}-{suffix}"
                card["id"] = card_id
            seen.add(card_id)
    return columns


def _load_source_columns(
    raw_source: Any, *, project_dir: Path
) -> tuple[list[Any], str]:
    """Columns (and board title) from a cardfile board directory.

    A cardfile board is a directory containing ``board.yaml`` + one Markdown
    file per card under ``cards/`` (see ``kanban_board``). Any problem — a
    non-string path, a path naming a file instead of a directory, or a missing
    board directory — raises ``ValueError`` naming the resolved path.
    ``configure`` is dispatched fail-fast, so the build stops loudly instead
    of shipping an empty or wrong board.
    """
    if not isinstance(raw_source, str) or not raw_source.strip():
        raise ValueError(
            f"kanban: `source:` must be a project-relative path naming the "
            f"board directory, got {raw_source!r}"
        )
    path = Path(raw_source.strip())
    if not path.is_absolute():
        path = project_dir / path
    if path.is_dir():
        path = project_dir / _canonical_card_dir(path, project_dir=project_dir)
    path = path.resolve()

    from folio.plugins import kanban_board

    if kanban_board.is_board_dir(path):
        board = kanban_board.load_board_dir(path, project_dir=project_dir.resolve())
        return board["columns"], board["title"], board.get("icons", {})

    if path.is_file():
        raise ValueError(
            f"kanban: '{path}' is a file; single-file boards were removed — "
            "`source:` must name a cardfile board directory (board.yaml + "
            "cards/), see the kanban formats page for the migration"
        )
    raise ValueError(
        f"kanban: no cardfile board at '{path}' (source '{raw_source}' "
        f"resolved against project directory '{project_dir.resolve()}'); "
        "run `folio kanban init` to create one"
    )


def _canonical_card_dir(path: Path, *, project_dir: Path) -> str:
    """Canonical project-relative board directory, with no symlink traversal."""
    project_root = project_dir.resolve()
    lexical = path if path.is_absolute() else project_root / path
    resolved = lexical.resolve()
    try:
        relative = resolved.relative_to(project_root)
    except ValueError:
        raise ValueError(
            f"kanban: cardfile source directory must stay inside the project: '{path}'"
        ) from None
    if _path_has_symlink(project_root, lexical):
        raise ValueError(
            f"kanban: cardfile source directory may not traverse a symlink: '{path}'"
        )
    return relative.as_posix()


def _normalize_column(raw_column: Any, index: int) -> dict[str, Any] | None:
    if not isinstance(raw_column, dict):
        warnings.warn(
            f"kanban: dropping column #{index + 1}: expected a mapping, "
            f"got {type(raw_column).__name__}",
            stacklevel=2,
        )
        return None

    title = raw_column.get("title")
    title = title.strip() if isinstance(title, str) and title.strip() else "Untitled"

    raw_id = raw_column.get("id")
    column_id = ""
    if isinstance(raw_id, str) and raw_id.strip():
        column_id = _slugify(raw_id)
    if not column_id:
        column_id = _slugify(title) or f"column-{index + 1}"

    raw_limit = raw_column.get("limit")
    limit: int | None = None
    if raw_limit is not None:
        if (
            isinstance(raw_limit, int)
            and not isinstance(raw_limit, bool)
            and raw_limit > 0
        ):
            limit = raw_limit
        else:
            warnings.warn(
                f"kanban: column '{title}': ignoring invalid WIP limit "
                f"{raw_limit!r} (expected a positive integer)",
                stacklevel=2,
            )

    raw_cards = raw_column.get("cards", [])
    if not isinstance(raw_cards, list):
        raw_cards = []
    cards = [
        card
        for raw_card in raw_cards
        if (card := _normalize_card(raw_card, column_title=title)) is not None
    ]
    return {"id": column_id, "title": title, "limit": limit, "cards": cards}


def _normalize_card(raw_card: Any, *, column_title: str) -> dict[str, Any] | None:
    if not isinstance(raw_card, dict):
        warnings.warn(
            f"kanban: column '{column_title}': dropping card: expected a "
            f"mapping, got {type(raw_card).__name__}",
            stacklevel=2,
        )
        return None
    title = raw_card.get("title")
    if not isinstance(title, str) or not title.strip():
        warnings.warn(
            f"kanban: column '{column_title}': dropping a card without a title",
            stacklevel=2,
        )
        return None
    title = title.strip()

    description = raw_card.get("description")
    description = description.strip() if isinstance(description, str) else ""

    raw_tags = raw_card.get("tags", [])
    tags = (
        [tag for tag in raw_tags if isinstance(tag, str)]
        if isinstance(raw_tags, list)
        else []
    )

    raw_assignee = raw_card.get("assignee")
    if isinstance(raw_assignee, str):
        assignee = [raw_assignee.strip()] if raw_assignee.strip() else []
    elif isinstance(raw_assignee, list):
        seen_names: dict[str, None] = {}
        for name in raw_assignee:
            if isinstance(name, str) and name.strip():
                seen_names.setdefault(name.strip(), None)
        assignee = list(seen_names)
    else:
        assignee = []

    link = _safe_link(raw_card.get("link"), column_title=column_title, title=title)

    raw_id = raw_card.get("id")
    card_id = (
        (_slugify(raw_id) if isinstance(raw_id, str) and raw_id.strip() else "")
        or _slugify(title)
        or "card"
    )

    priority = raw_card.get("priority")
    priority = (
        priority.strip().lower()
        if isinstance(priority, str)
        and priority.strip().lower() in ("low", "normal", "high")
        else ""
    )

    parent = raw_card.get("parent")
    parent = parent.strip() if isinstance(parent, str) else ""

    raw_blocked = raw_card.get("blocked_by", [])
    blocked_by = (
        [item for item in raw_blocked if isinstance(item, str)]
        if isinstance(raw_blocked, list)
        else []
    )

    created = raw_card.get("created")
    created = str(created) if created is not None else ""

    milestone = raw_card.get("milestone")
    milestone = str(milestone).strip() if milestone is not None else ""

    raw_type = raw_card.get("type")
    if raw_type is None or isinstance(raw_type, (str, int, float)):
        card_type = str(raw_type).strip() if raw_type is not None else ""
    else:
        warnings.warn(
            f"kanban: card '{title}': type {raw_type!r} is not a scalar — ignored",
            stacklevel=2,
        )
        card_type = ""

    raw_size = raw_card.get("size")
    if raw_size is None or (isinstance(raw_size, str) and not raw_size.strip()):
        # "" is the normalized unset value; active_kanban re-normalizes
        # already-normalized cards, so blank must stay silent (idempotence).
        size = ""
    elif isinstance(raw_size, str) and raw_size.strip().upper() in (
        "S",
        "M",
        "L",
        "XL",
    ):
        size = raw_size.strip().upper()
    else:
        warnings.warn(
            f"kanban: card '{title}': size {raw_size!r} is not one of S, M, L, XL — ignored",
            stacklevel=2,
        )
        size = ""

    raw_source = raw_card.get("source")
    if raw_source is None or isinstance(raw_source, (str, int, float)):
        source = str(raw_source).strip() if raw_source is not None else ""
    else:
        warnings.warn(
            f"kanban: card '{title}': source {raw_source!r} is not a scalar — ignored",
            stacklevel=2,
        )
        source = ""

    return {
        "id": card_id,
        "title": title,
        "description": description,
        "tags": tags,
        "assignee": assignee,
        "type": card_type,
        "size": size,
        "source": source,
        "link": link,
        "priority": priority,
        "parent": parent,
        "blocked_by": blocked_by,
        "created": created,
        "milestone": milestone,
        "artifacts": _normalize_artifacts(
            raw_card.get("artifacts"), column_title=column_title, title=title
        ),
        "criteria": _normalize_criteria(raw_card.get("criteria")),
        "trail": _normalize_trail(raw_card.get("trail")),
        "comments": _normalize_comments(raw_card.get("comments")),
        # The roadmap step this card's milestone names. Filled by
        # _resolve_roadmap_phases once the roadmap section is known; a bare
        # "0.4" tells a reader nothing, and the phase it belongs to already
        # has a name and an anchor in the same docs.yaml. Carried through
        # re-normalization rather than recomputed, because active_kanban has
        # no view of the roadmap section.
        "phase": str(raw_card.get("phase", "") or ""),
        "phaseTitle": str(raw_card.get("phaseTitle", "") or ""),
        # Where this card's own file lives, as a project-relative path.
        # Filled by _resolve_card_paths; empty on a board that is not a card
        # directory. A path, not a URL — see that function.
        "file": str(raw_card.get("file", "") or ""),
    }


def _normalize_artifacts(
    raw_artifacts: Any, *, column_title: str, title: str
) -> list[dict[str, Any]]:
    """Typed artifact refs -> ``{kind, target, display, label, href}``.

    Accepts both the committed one-line form (``- doc: research/x.md``) and
    the already-normalized form, so re-normalization is idempotent. ``url``
    targets go through the shared href scheme policy (fail-fast on
    ``javascript:``/``data:``); repo-relative kinds get their href filled in
    by ``configure`` once the project repo URL is known. ``display`` is the
    target as the author wrote it, set by the board loader; where it is
    absent (a project plugin's override) the target is what was written.
    """
    if not isinstance(raw_artifacts, list):
        return []
    from folio.plugins.kanban_board import parse_artifact

    context = f"kanban: column '{column_title}' card '{title}' artifact"
    artifacts = []
    for raw in raw_artifacts:
        if isinstance(raw, dict) and "kind" in raw and "target" in raw:
            kind = str(raw["kind"])
            target = str(raw["target"])
            label = str(raw.get("label", ""))
            display = str(raw.get("display", "") or "") or target
        else:
            kind, target, label = parse_artifact(raw, card_id=title)
            display = target
        # hrefs are always recomputed, never trusted from input data: a
        # pre-"normalized" mapping could otherwise smuggle an arbitrary
        # href past the scheme policy. Only `url:` has one at all — a path
        # or a PR number is rendered as what it is, because turning it into
        # a hosting-provider URL is exactly what the board stopped doing.
        href = ""
        if kind == "url":
            from folio.config import _theme_href

            href = _theme_href(target, context)
        artifacts.append(
            {
                "kind": kind,
                "target": target,
                "display": display,
                "label": label,
                "href": href,
            }
        )
    return artifacts


def _normalize_criteria(raw_criteria: Any) -> list[dict[str, Any]]:
    if not isinstance(raw_criteria, list):
        return []
    return [
        {"text": str(item.get("text", "")), "done": bool(item.get("done"))}
        for item in raw_criteria
        if isinstance(item, dict) and str(item.get("text", "")).strip()
    ]


def _normalize_trail(raw_trail: Any) -> list[dict[str, Any]]:
    if not isinstance(raw_trail, list):
        return []
    return [
        {
            "date": str(item.get("date", "")),
            "actor": str(item.get("actor", "")),
            "ref": str(item.get("ref", "")),
            "note": str(item.get("note", "")),
            # Always empty. A ref used to resolve to {repo}/commit/<sha> or
            # {repo}/pull/<n>; the board no longer builds hosting-provider
            # URLs, so a sha renders as the sha it is. The key stays so data
            # from an older build still typechecks against this contract.
            "href": "",
        }
        for item in raw_trail
        if isinstance(item, dict)
    ]


def _normalize_comments(raw_comments: Any) -> list[dict[str, Any]]:
    if not isinstance(raw_comments, list):
        return []
    return [
        {
            "date": str(item.get("date", "")),
            "actor": str(item.get("actor", "")),
            "text": str(item.get("text", "")),
        }
        for item in raw_comments
        if isinstance(item, dict)
    ]


def _safe_link(raw_link: Any, *, column_title: str, title: str) -> str:
    """Sanitize a card link with the same scheme rules as other hrefs.

    Delegates to the shared href validator (http(s)/mailto or a scheme-less
    relative path); anything else — ``javascript:``, ``data:``, ... — raises,
    which fails the build loudly under configure's fail-fast dispatch.
    """
    if raw_link is None:
        return ""
    from folio.config import _theme_href

    return _theme_href(raw_link, f"kanban: column '{column_title}' card '{title}' link")


def active_kanban(config: Any) -> dict[str, Any] | None:
    """The normalized kanban config, or None when the plugin is inactive.

    The plugin loads for every build (it is a default plugin) but only a
    ``kanban:`` section in docs.yaml — surfaced as ``config.extra["kanban"]``
    by configure() — activates its output.
    """
    kanban = getattr(config, "extra", {}).get("kanban")
    if not isinstance(kanban, dict):
        return None

    routes = dict(DEFAULT_ROUTES)
    raw_routes = kanban.get("routes", {})
    if isinstance(raw_routes, dict):
        for key in routes:
            if key in raw_routes:
                routes[key] = _normalize_route_value(raw_routes[key])

    title = kanban.get("title")
    if not isinstance(title, str) or not title.strip():
        title = DEFAULT_TITLE
    else:
        title = title.strip()

    # Re-normalize the columns rather than passing them through verbatim:
    # project plugins may override config.extra["kanban"] after configure()
    # (see the tryfirst note above) with partial card/column shapes, and the
    # emitted lib/kanban-data.ts module feeds kanban-board.tsx, which
    # dereferences card.tags/column.cards unguarded. Normalizing here keeps
    # the emitted data on the KanbanColumn[] contract regardless of who set
    # the extra entry. Idempotent for already-normalized data.
    raw_columns = kanban.get("columns", [])
    if not isinstance(raw_columns, list):
        raw_columns = []
    columns = _normalize_columns(raw_columns)
    # `cardDir` comes through as-is. It is the one field here that records a
    # fact about the repository rather than about the board's contents —
    # whether `source:` resolved to a directory of card files — and it is
    # what decides the file links below. Dropping it made the rebuild below a
    # no-op for file links, which is exactly what the next comment promises
    # it is not.
    description = kanban.get("description")
    result = {
        "routes": routes,
        "title": title,
        "columns": columns,
        "description": description.strip() if isinstance(description, str) else "",
        "cardDir": str(kanban.get("cardDir") or ""),
        "icons": dict(kanban.get("icons") or {})
        if isinstance(kanban.get("icons"), dict)
        else {},
    }
    _resolve_card_icons(result["columns"], result["icons"])
    # Re-normalization wiped each card's derived path and artifact hrefs (they
    # are never trusted from input data); rebuild them here so the emitted data
    # module carries them regardless of who set config.extra["kanban"].
    _resolve_card_paths(result)
    project_dir = Path(getattr(config, "project_dir", "") or ".")
    _resolve_artifact_hrefs(
        result,
        docs_route_base=_docs_route_base(config),
        project_dir=project_dir,
        doc_sources=_doc_source_dirs(config, project_dir),
    )
    return result


def get_kanban(config: Any) -> dict[str, Any]:
    kanban = active_kanban(config)
    if kanban is not None:
        return kanban
    return {"routes": dict(DEFAULT_ROUTES), "title": DEFAULT_TITLE, "columns": []}


def get_columns(config: Any) -> list[dict[str, Any]]:
    columns = get_kanban(config)["columns"]
    return columns if isinstance(columns, list) else []


def docs_page_mdx(kanban: dict[str, Any]) -> str:
    title = str(kanban.get("title") or DEFAULT_TITLE)
    return (
        'import { KanbanBoard } from "@/components/kanban-board"\n\n'
        f"# {_escape_mdx_text(title)}\n\n"
        f"This page is {_GENERATED_PAGE_MARKER} "
        "when no source kanban document exists.\n\n"
        "<KanbanBoard />\n"
    )


def _escape_mdx_text(value: str) -> str:
    """Backslash-escape characters MDX treats as syntax in body text."""
    return _MDX_TEXT_SPECIALS_RE.sub(r"\\\1", value)


@hookimpl
def register_cli(app: Any) -> None:
    from folio.plugins.kanban_cli import register

    register(app)
