from __future__ import annotations

from pathlib import Path
from typing import Any

from folio.plugin import hookimpl

DEFAULT_ROUTES = {"docs": True, "public": False}
ROADMAP_TYPES = (
    'export type RoadmapStatus = "shipped" | "active" | "next" | "later"\n\n'
    "export interface RoadmapPhase {\n"
    "  id: string\n"
    "  version: string\n"
    "  title: string\n"
    "  status: RoadmapStatus\n"
    "  layer: string\n"
    "  summary: string\n"
    "  command?: string\n"
    "  features: string[]\n"
    "}\n"
)


@hookimpl
def config_keys() -> list[str]:
    return ["roadmap"]


@hookimpl
def configure(config: Any, raw_config: dict[str, Any]) -> None:
    config.extra["roadmap"] = normalize_roadmap(raw_config.get("roadmap", {}))


@hookimpl
def register_extensions(registry: Any, config: Any) -> None:
    roadmap = get_roadmap(config)
    registry.register_component(
        "Roadmap",
        import_path="@/components/roadmap",
        expose_mdx=True,
    )
    registry.write_data_module(
        "roadmap",
        export_name="roadmapPhases",
        data=roadmap["phases"],
        type_source=ROADMAP_TYPES,
        type_annotation="RoadmapPhase[]",
        module_path="roadmap-data",
    )

    if roadmap["routes"].get("public"):
        registry.add_view(
            path="/roadmap",
            layout="folio.public",
            title=f"{config.project_name} Roadmap",
            props={
                "eyebrow": "Official roadmap plugin",
                "description": (
                    "A read-only kanban generated from source configuration. "
                    "Update docs.yaml and rebuild to change the board."
                ),
            },
            slots={"main": [{"component": "Roadmap"}]},
        )


@hookimpl
def emit_assets(builder: Any, config: Any) -> None:
    """Compatibility hook for generated docs pages.

    Public routes and data modules are emitted through register_extensions().
    """
    routes = get_roadmap(config)["routes"]

    if routes.get("docs") and not builder.page_exists("roadmap"):
        builder.write_page("roadmap", docs_page_mdx())


def normalize_roadmap(raw_roadmap: Any) -> dict[str, Any]:
    if not isinstance(raw_roadmap, dict):
        return {"routes": dict(DEFAULT_ROUTES), "phases": []}

    routes = dict(DEFAULT_ROUTES)
    raw_routes = raw_roadmap.get("routes", {})
    if isinstance(raw_routes, dict):
        for key in routes:
            if key in raw_routes:
                routes[key] = bool(raw_routes[key])

    phases = raw_roadmap.get("phases", [])
    if not isinstance(phases, list):
        phases = []

    return {"routes": routes, "phases": phases}


def get_roadmap(config: Any) -> dict[str, Any]:
    roadmap = getattr(config, "extra", {}).get("roadmap")
    if isinstance(roadmap, dict):
        normalized = normalize_roadmap(roadmap)
        normalized["phases"] = roadmap.get("phases", normalized["phases"])
        return normalized
    return {"routes": dict(DEFAULT_ROUTES), "phases": []}


def get_phases(config: Any) -> list[dict[str, Any]]:
    phases = get_roadmap(config)["phases"]
    return phases if isinstance(phases, list) else []


def docs_page_mdx() -> str:
    return (
        'import { Roadmap } from "@/components/roadmap"\n\n'
        "# Roadmap\n\n"
        "This page is generated by the official `folio.plugins.roadmap` plugin "
        "when no source roadmap document exists.\n\n"
        "<Roadmap />\n"
    )


def register_cli(app: Any) -> None:
    import typer
    from rich.console import Console
    from rich.table import Table

    from folio.config import load_config
    from folio.features import disabled_feature_message, is_feature_enabled

    console = Console()

    @app.command(name="roadmap", hidden=True)
    def roadmap(
        directory: Path = typer.Argument(
            default=None, help="Project directory (defaults to cwd)"
        ),
        project_dir: Path = typer.Option(
            default=None,
            help="Compatibility option for scripts that prefer named arguments",
        ),
        config: str = typer.Option(
            "docs.yaml", "--config", "-c", help="Config file path"
        ),
    ) -> None:
        """Preview source-defined roadmap phases."""
        if not is_feature_enabled("roadmap"):
            console.print(f"[yellow]{disabled_feature_message('roadmap')}[/yellow]")
            raise typer.Exit(1)

        if directory is not None and project_dir is not None:
            directory_path = directory.resolve()
            project_dir_path = project_dir.resolve()
            if directory_path != project_dir_path:
                console.print(
                    "[red]Error: Pass the project directory either as an argument "
                    "or --project-dir, not both.[/red]"
                )
                raise typer.Exit(1)

        target = (project_dir or directory or Path.cwd()).resolve()
        try:
            cfg = load_config(target / config)
        except FileNotFoundError as e:
            console.print(f"[red]Error: {e}[/red]")
            raise typer.Exit(1)

        phases = get_phases(cfg)
        if not phases:
            console.print("[yellow]No roadmap phases configured in docs.yaml.[/yellow]")
            return

        table = Table(title=f"{cfg.project_name} Roadmap")
        table.add_column("Status", style="cyan")
        table.add_column("Version")
        table.add_column("Title", style="bold")
        table.add_column("Command")

        for phase in phases:
            table.add_row(
                str(phase.get("status", "")),
                str(phase.get("version", "")),
                str(phase.get("title", "")),
                str(phase.get("command", "")),
            )

        console.print()
        console.print(table)
        console.print()
